# schemas/task.py — Pydantic schemas for task-related request and response data.
#
# There are three separate schemas for tasks:
#
#   TaskCreate  — fields accepted when creating a new task (POST /tasks/)
#   TaskUpdate  — fields accepted when updating a task (PATCH /tasks/{id})
#   TaskOut     — fields returned to the client in every task response
#
# Why three schemas instead of one?
#   - TaskCreate: title is required, everything else has sensible defaults
#   - TaskUpdate: EVERY field is Optional because PATCH only updates what you send.
#     Sending {"status": "completed"} should not wipe the title.
#   - TaskOut: the read-only fields (id, created_at, owner_id) only belong in responses.

from datetime import datetime
from typing import Optional
from pydantic import BaseModel


# --- Input schema: creating a task ---
class TaskCreate(BaseModel):
    # title is required — a task must have a name.
    title: str

    # All other fields are optional. If the client does not send them,
    # the defaults below are used.
    description: Optional[str] = None       # No description by default
    priority: Optional[str] = "medium"      # Default priority: medium
    status: Optional[str] = "pending"       # New tasks always start as pending
    due_date: Optional[datetime] = None     # No deadline by default


# --- Input schema: updating a task (PATCH) ---
class TaskUpdate(BaseModel):
    # Every field is Optional with a default of None.
    # model_dump(exclude_unset=True) in the route will only return the fields
    # the client actually sent — so only those fields get updated in the DB.
    # Example: sending {"status": "completed"} will ONLY update status,
    # leaving title, description, priority, and due_date unchanged.
    title: Optional[str] = None
    description: Optional[str] = None
    priority: Optional[str] = None
    status: Optional[str] = None
    due_date: Optional[datetime] = None
    # completed_at can technically be set manually, but the route also
    # sets it automatically when status changes to "completed".
    completed_at: Optional[datetime] = None


# --- Output schema: what the client receives about a task ---
class TaskOut(BaseModel):
    id: int                          # Auto-generated by the database
    title: str
    description: Optional[str]
    priority: str
    status: str
    due_date: Optional[datetime]
    created_at: datetime             # Set by the database on INSERT
    completed_at: Optional[datetime] # Set automatically when status → "completed"
    owner_id: int                    # The ID of the user who owns this task

    # from_attributes=True allows Pydantic to read from SQLAlchemy ORM objects.
    # Without this, returning a Task ORM object directly would raise a validation error.
    model_config = {"from_attributes": True}
